config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :likes, only: %i[create destroy]

  resources :users, only: %i[new create edit update show] do
    resource :follows, only: %i[create destroy], controller: 'follows'
    
     # Вложенный ресурс для просмотра всех постов пользователя
    resources :posts, only: :index 
  end

  resources :posts do
    resources :subcomments, only: %i[create destroy]

    resources :comments, except: %i[new show]
  end

  resources :comments, except: %i[new show] do
    resources :subcomments, only: %i[create destroy]
  end

  namespace :admin do
    resources :users, only: %i[index create edit update destroy]
  end

  root 'homes#index'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Authorship
  include Subcommentable

  belongs_to :post
  belongs_to :user

  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  include PostsComments
  # модуль для якоря, чтобы добавить dom_id
  include ActionView::RecordIdentifier

  before_action :set_post!
  before_action :set_comment!, except: :create
  before_action :authorize_comment!
  # метод пандит на права доступа
  after_action :verify_authorized

  def edit; end

  def create
    @comment = @post.comments.build comment_create_params

    if @comment.save
      flash[:success] = 'Comment created'
      redirect_to post_path(@post)
    else
      load_post_comments(do_render: true)
    end
  end

  def update
    if @comment.update comment_update_params
      flash[:success] = 'Comment edited'
      # При редиректе генерирует ссылку включая якорь
      redirect_to post_path(@post, anchor: dom_id(@comment))
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = 'Comment delete'
    redirect_to post_path(@post)
  end

  private

  def comment_create_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end

  def comment_update_params
    params.require(:comment).permit(:body)
  end

  def set_post!
    @post = Post.find params[:post_id]
  end

  def set_comment!
    @comment = @post.comments.find params[:id]
  end

  def authorize_comment!
    authorize(@comment || Post)
  end
end

app/views/comments/_comment.html.erb
<% #частичное представление для комментариев %>
<%= tag.article class: 'mb-3 card border-0', id: dom_id(comment) do %>
  <div class="card-header">
    <div class="row">
      <div class="col-sm-9">
        <strong> <%= comment.user.name %></strong>
      </div>
      <div class="col-sm-3 text-end">
        <small><time datetime="<%= comment.formatted_created_at %>">
          <%= comment.formatted_created_at %>
        </time></small>
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="row g-0">
      <div class="col-sm">
        <p class="mb-4 mt-4"><%= comment.body %></p>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="float-end">
      <% if policy(comment).edit? %>
      <%= link_to 'Edit', edit_post_comment_path(post, comment), class: 'btn btn-secondary btn-sm'%>
        <% end %>

      <% if policy(comment).destroy? %>
      <%= link_to 'Delete', post_comment_path(post, comment), class: 'btn btn-danger btn-sm',
                  data: {method: :delete, confirm: 'Are you sure?'} %>
        <% end %>
    </div>
    <div class="clearfix"></div>
  </div>
  </div>
<% end %>

<%= render 'subcomments/subcommentable', subcommentable: comment, subcomment: @subcomment,
           html_id: dom_id(comment, 'subcomment_form') %>

app/views/comments/_form.html.erb
<%= render 'shared/errors', object: @comment %>

<%= form_with model: [@post, @comment] do |f| %>
  <div class="col-sm-10">
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="mb-4 mt-4">
    <%= f.submit "Submit comment", class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%provide :page_title, @post.title %>
<% currently_at 'Feed' %>

<h3 class="mb-4 text-danger">Comment edit</h3>

<%= render 'form' %>