config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :likes, only: %i[create destroy]

  resources :users, only: %i[new create edit update show] do
    resource :follows, only: %i[create destroy], controller: 'follows'
    
     # Вложенный ресурс для просмотра всех постов пользователя
    resources :posts, only: :index 
  end

  resources :posts do
    resources :subcomments, only: %i[create destroy]

    resources :comments, except: %i[new show]
  end

  resources :comments, except: %i[new show] do
    resources :subcomments, only: %i[create destroy]
  end

  namespace :admin do
    resources :users, only: %i[index create edit update destroy]
  end

  root 'homes#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include Authorship
  include Subcommentable
  include ImageUploader::Attachment(:image)

  has_many :likes, dependent: :destroy

  # Позволит удалить пост вместе с комментариями
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  # метод класса который можем вызвать
  scope :all_by_tags, lambda { |tags|
    posts = includes(:user)
    posts = if tags
              posts.joins(:tags).where(tags: tags).preload(:tags)
            else
              posts.includes(:post_tags, :tags)
            end

    posts.order(created_at: :desc)
  }
end

app/views/shared/_errors.html.erb
<% if object&.errors&.full_messages&.any?%>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Home', root_path,
                          class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Feed', posts_path,
                          class: 'nav-link px-2', current_page: current_page %></li>

          <% if policy([:admin, :user]).index? %>
            <li><%= nav_tab "User menu", admin_users_path,
                            class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>

        <div class="text-center">
          <% if policy(:post).new? %>
          <%= link_to 'New post', new_post_path, class: 'btn btn-danger' %>
         <% end %>
        </div>

<form class="d-flex ms-lg-auto" action="<%= posts_path %>" method="get">
  <div class="input-group input-group-sm">
    <%= select_tag 'tag_ids[]', options_from_collection_for_select(@tags || [], :id, :title, params[:tag_ids]),
     {include_blank: true, multiple: true, class: 'form-select', style: 'height: 30px;'} %>
    <button class="btn btn-outline-secondary" type="submit">Search</button>
  </div>
</form>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= nav_tab current_user.name_or_email, '#',
                          class: 'nav-link px-2 dropdown-toggle',
                          data: {"bs-toggle": 'dropdown'}, current_page: current_page %>

              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Edit profile', edit_user_path(current_user),
                              class: 'dropdown-item' %>
                </li>
                <li>
                  <%= link_to 'Log Out', session_path,
                              class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab 'Sign Up', new_user_path,
                            class: 'nav-link px-2', current_page: current_page %></li>

            <li><%= nav_tab 'Log In', new_session_path,
                            class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>