config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :likes, only: %i[create destroy]

  resources :users, only: %i[new create edit update show] do
    resource :follows, only: %i[create destroy], controller: 'follows'
    
     # Вложенный ресурс для просмотра всех постов пользователя
    resources :posts, only: :index 
  end

  resources :posts do
    resources :subcomments, only: %i[create destroy]

    resources :comments, except: %i[new show]
  end

  resources :comments, except: %i[new show] do
    resources :subcomments, only: %i[create destroy]
  end

  namespace :admin do
    resources :users, only: %i[index create edit update destroy]
  end

  root 'homes#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include Authorship
  include Subcommentable
  include ImageUploader::Attachment(:image)

  has_many :likes, dependent: :destroy

  # Позволит удалить пост вместе с комментариями
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  # метод класса который можем вызвать
  scope :all_by_tags, lambda { |tags|
    posts = includes(:user)
    posts = if tags
              posts.joins(:tags).where(tags: tags).preload(:tags)
            else
              posts.includes(:post_tags, :tags)
            end

    posts.order(created_at: :desc)
  }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include PostsComments
  before_action :require_authentication, except: %i[show index]
  before_action :set_post!, only: %i[show destroy edit update]
  before_action :fetch_tags, only: %i[new edit]
  before_action :authorize_post!
  # метод пандит на права доступа
  after_action :verify_authorized

  def index
    if params[:user_id].present?
      @user = User.find_by(id: params[:user_id])
      unless @user
        flash[:alert] = "Пользователь не найден"
        redirect_to root_path
        return
      end
    end
  
    posts_relation = @user ? @user.posts : Post
    @pagy, @posts = pagy posts_relation.all_by_tags(params[:tag_ids])
    @posts = @posts.decorate
    @tags = Tag.all
  end
  
  

  def show
    load_post_comments
  end

  def new
    @post = Post.new
    @tags = Tag.all
  end

  def edit; end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      flash[:success] = 'Post created'
      redirect_to posts_path
    else
      render :new
    end
  end

  def update
    # Удаление пустых значений и дубликатов из tag_ids
    params[:post][:tag_ids].reject!(&:empty?).uniq!

    if @post.update post_params
      flash[:success] = 'Post edited'
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post deleted'
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, tag_ids: [])
  end

  def set_post!
    # убрал find_by :id чтобы небыло ошибки с несуществующим id, создал метод в concerns/error
    @post = Post.find params[:id]
  end

  def fetch_tags
    @tags = Tag.all
  end

  # authorize метод пандит, имеет ли пользователь право на вылолнение
  def authorize_post!
    authorize(@post || Post)
  end
end

app/views/posts/_form.html.erb
<%= render 'shared/errors', object: @post %>

<article class="card mt-3 mb-3 text-center mx-auto" style="max-width: 600px;">
<%= form_with model: @post do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-10 mb-4 mt-4 mx-4">
      <%= f.text_field :title, placeholder: "Title your post", class: 'form-control' %>
    </div>
  </div>
  
<div class="img-container ">
        <% if @post.image.present? %>
          <%= image_tag @post.image_url %>
        <% end %>
      </div>

  <div class="mb-3 row">
    <div class="col-sm-10 mb-4 mt-4 mx-4">
      <%= f.text_area :body, placeholder: "What do you want to share?", class: 'form-control' %>
      <div class="mb-4 mt-4 mx-4"><%= f.file_field :image %></div>
    </div>
  </div>

  <div class="col-sm-10 mb-4 mt-4 mx-4">
    <div class="input-group">
      <%= f.collection_select :tag_ids, @tags, :id, :title, {}, multiple: true,
                              class: 'form-select js-multiple-select js-ajax-select',
                              id: 'post_tag_ids' %>
      <!-- <label for="post_tag_ids" class="form-label">Select Tags</label> -->
      <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-chevron-down"></i>
      </button>
      <ul class="dropdown-menu">
        <% @tags.each do |tag| %>
          <li><%= f.check_box :tag_ids, { multiple: true }, tag.id, nil %> <%= tag.title %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="mb-4 mt-4 mx-4">
  <%= f.submit 'Save post', class: 'btn btn-dark' %>
<% end %>
</div>
</article>

app/views/posts/_post.html.erb
<article class="card mt-3 mb-3 text-center mx-auto" style="max-width: 400px;"> 
  <section class="card-header">
  <%= link_to post.user.name_or_email, user_posts_path(post.user), class: "user-profile-link" %>
</section>

  <div class="card-body">

    <div class="img-container">
        <% if post.image.present? %>
          <%= image_tag post.image_url %>
        <% end %>
      </div>

    <h5 class="mt-3"><%= post.title %></h5>

    <div class="my-2">
      <%= render post.tags %>
    </div>

    <section class="card-text">
      <p class="my-2">
        <%= truncate(strip_tags(post.body), length: 70) %>
      </p>
      
    </section>

    <div class="mt-4">
      <%= link_to "Answers & Edit", post_path(post), class: 'btn btn-dark btn-sm' %>

      <% if policy(post).edit? %>
        <%= link_to "Edit", edit_post_path(post), class: 'btn btn-secondary btn-sm' %>
      <% end %>

      <% if policy(post).destroy? %>
        <%= link_to "Delete", post_path(post), class: 'btn btn-danger btn-sm',
                  data: {method: :delete, confirm: "Are you sure?"} %>
      <% end %>
    </div>
  </div>

 <%= render partial: 'likes/like', locals: { post: post } %>

  <div class="mx-3 mb-4 text-secondary">
    <time datetime="<%= post.formatted_created_at %>">
      <small><%= post.formatted_created_at %></small>
    </time>
  </div>
</article>

app/views/posts/edit.html.erb
<%provide :page_title, 'Post edit' %>
<% currently_at 'Feed' %>

<h3 class="mb-4 text-danger">Post edit</h3>

<%= render 'form', tags: @tags %>

app/views/posts/index.html.erb
<% provide :page_title, 'Feed' %>
<% currently_at 'Feed' %>

<div class="text-center">
<%= link_to root_path do %>
    <%= image_tag "logo.jpeg", alt: "Логотип SnapFeed", class: "logo-img", style: "width: 80px; height: 80px;" %>
  <% end %>

</div>

<%= pagination @pagy %>

<%= render @posts %>

<%= pagination @pagy %>

app/views/posts/new.html.erb
<%provide :page_title, 'New post' %>
<% currently_at 'Feed' %>

<h2 class="mb-4 text-danger">New post</h2>

<%= render 'form', tags: @tags %>

app/views/posts/show.html.erb
<%provide :page_title, @post.title %>
<% currently_at 'Feed' %>

<article class="card mt-3 mb-3 text-center mx-auto" style="max-width: 300px;"> <!-- Уменьшенная максимальная ширина -->
  <section class="card-header">
    <%= link_to @post.user.name_or_email, user_posts_path(@post.user), class: "user-profile-link" %>
  </section>

  <div class="card-body">
    <div class="img-container">
      <% if @post.image.present? %>
        <%= image_tag @post.image_url, style: "max-width: 100%;" %> <!-- Измененный размер изображения -->
      <% end %>
    </div>

    <h5 class="mt-3"><%= @post.title %></h5>

    <div class="my-2">
      <%= render @post.tags %>
    </div>

    <section class="card-text">
      <p class="my-2">
        <%= truncate(strip_tags(@post.body), length: 70) %>
      </p>
    </section>

    <div class="mt-4">
      
      <% if policy(@post).edit? %>
        <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-secondary btn-sm' %>
      <% end %>

      <% if policy(@post).destroy? %>
        <%= link_to "Delete", post_path(@post), class: 'btn btn-danger btn-sm',
                    data: {method: :delete, confirm: "Are you sure?"} %>
      <% end %>
    </div>
  </div>

  <%= render partial: 'likes/like', locals: { post: @post } %>

  <div class="mx-3 mb-4 text-secondary">
    <time datetime="<%= @post.formatted_created_at %>">
      <small><%= @post.formatted_created_at %></small>
    </time>
  </div>
</article>


<hr class="my-4">

<h5 class="mb-4 mt-4 text-danger">
  Write your comment
</h5>


<%= render 'comments/form' %>

<hr class="my-3">

<h3 class="mb-4 mt-4 text-danger">
  Comments
</h3>

<%= pagination @pagy %>

<% #используется частичное представление с именем 'comments/comment',
   #рендерим коллекцию, элементы коллецкии называются comment(помещатся по очереди в эту переменную),
   #мы передаем переменную @post, чтобы иметь доступ к контексту поста изнутри частичного представления.  %>
<%= render partial: 'comments/comment', collection: @comments,
           as: :comment, locals: {post: @post} %>

<%= pagination @pagy %>